title: File Upload Guide using Transmit
description: This guide will walk you through the process of uploading files to an S3 bucket and using SFTP with SSH keys.
theme: just-the-docs

url: https://php-media-server.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
